"""initial

Revision ID: 283d2a48456c
Revises:
Create Date: 2025-01-05 20:37:13.927393

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "283d2a48456c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("username", sa.VARCHAR(), nullable=False),
        sa.Column("age", sa.INTEGER(), nullable=False),
        sa.Column("sex", sa.VARCHAR(), nullable=False),
        sa.Column("latitude", sa.FLOAT(), nullable=True),
        sa.Column("longitude", sa.FLOAT(), nullable=True),
        sa.Column("city", sa.VARCHAR(), nullable=True),
        sa.Column("country", sa.VARCHAR(), nullable=False),
        sa.Column("currency", sa.VARCHAR(), nullable=False),
        sa.Column("bio", sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "trips",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("username", sa.VARCHAR(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.Column("description", sa.VARCHAR(), nullable=True),
        sa.Column("locations", postgresql.ARRAY(sa.JSON()), nullable=True),
        sa.Column("friends", postgresql.ARRAY(sa.VARCHAR()), nullable=True),
        sa.ForeignKeyConstraint(["username"], ["users.username"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "expenses",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("username", sa.VARCHAR(), nullable=False),
        sa.Column("trip_id", sa.BIGINT(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.Column("cost", sa.FLOAT(), nullable=False),
        sa.Column("currency", sa.VARCHAR(), nullable=False),
        sa.Column(
            "date", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("debtors", postgresql.ARRAY(sa.VARCHAR()), nullable=True),
        sa.ForeignKeyConstraint(["trip_id"], ["trips.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["username"], ["users.username"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "notes",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("user_id", sa.BIGINT(), nullable=False),
        sa.Column("trip_id", sa.BIGINT(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.Column("path", sa.VARCHAR(), nullable=False),
        sa.Column("file_type", sa.VARCHAR(), nullable=False),
        sa.Column("width", sa.INTEGER(), nullable=True),
        sa.Column("height", sa.INTEGER(), nullable=True),
        sa.Column("is_private", sa.BOOLEAN(), nullable=True),
        sa.ForeignKeyConstraint(["trip_id"], ["trips.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notes")
    op.drop_table("expenses")
    op.drop_table("trips")
    op.drop_table("users")
    # ### end Alembic commands ###
