volumes:
  files:
  postgres_data:
  redis_data:


services:
  bot:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - files:/files
      - ./:/app
    depends_on:
      - postgres
      - redis
    command: bash -c "alembic -c "./src/config/alembic.ini" upgrade head && python ./bot.py"
    container_name: travel_bot

  postgres:
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: postgres_bot

  redis:
    image: redis:alpine
    restart: always
    env_file:
      - .env
    volumes:
      - redis_data:/data
    container_name: redis_bot
